### ISSUE TITLE
preprocessing won't run out-of-the-box due to html5lib

### ISSUE THREAD

**Issue by morrisalp** [mrjleo/boilernet#1]
Running preprocessing in a new environment with the listed requirements fails due to line 76 in preprocess.py: `doc = BeautifulSoup(hfile, features='html5lib')`

The error thrown: "Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?"

This is fixed by replacing this line with `doc = BeautifulSoup(hfile, features='html.parser')` as suggested here: https://github.com/coursera-dl/edx-dl/issues/434

**Comment by mrjleo** [comment]
Thanks for the report! Could you try manually installing the parser (`pip install html5lib`)?

**Comment by morrisalp** [comment]
That works as well. Thanks.
