### ISSUE TITLE
How do I make "prepared" htmls?

### ISSUE THREAD

**Issue by dreamwayjgs** [mrjleo/boilernet#10]
Hello! I'm trying to train a model with given datasets on README before using other datasets.
In example, it seems that <code>process.py</code> needs "prepared" html data.
But, I cannot find how to make the prepared html. I guess the prepared data have only visual elements in the html, though.

Could you explain how to make the prepared html files from raw html files?

**Comment by mrjleo** [comment]
Hi, it depends on your data. If you want to train on one of the two datasets we provide, the prepared HTML files are already there. If you want to use your own data, you'll need to prepare it as follows:

- remove all HTML comments
- remove some irrelevant HTML tags (e.g. head, style, ...)
- Wrap each leaf node (i.e. the text elements) in a span tag and add a content attribute, `span['__boilernet_label'] = 1` or `span['__boilernet_label'] = 0`

You can have a look at `net/misc/prepare_dataset.py`, but this script will only work for our datasets, you'll need to modify it if you use your own data.

**Comment by dreamwayjgs** [comment]
Oh, I got it. Thanks!
