### ISSUE TITLE
Can you share the scripts used for generating files in `prepared_html`?

### ISSUE THREAD

**Issue by prabhakar267** [mrjleo/boilernet#15]

**Comment by mrjleo** [comment]
Hi, is this what you're looking for?
https://github.com/mrjleo/boilernet/blob/619a012dfbf8892585ca6f85567632ab94564a0d/net/misc/prepare_dataset.py

**Comment by prabhakar267** [comment]
@mrjleo Thanks for the reply. No, this is not what I'm looking for.
My understanding is the raw pages, were processed to a cleaner version which is then used for annotation. 
`prepare_dataset.py` seems to be doing the processing after the pages are annotated.

I'm looking for the script that was used before annotation to generate the cleaner/simpler version of pages .

**Comment by mrjleo** [comment]
I see. There is no other script, and in fact we annotated the pages directly in the browser. The only thing I can think of is the removal of a couple of tags. But this is done after annotating: https://github.com/mrjleo/boilernet/blob/619a012dfbf8892585ca6f85567632ab94564a0d/net/misc/util.py#L10

I hope this helps.

**Comment by prabhakar267** [comment]
I was trying to get the annotation label for each node in files from raw HTML directory. I was able to do that with a custom script.
Thanks for your inputs @mrjleo

**Comment by turian** [comment]
@prabhakar267 Do you mind sharing your custom script?
