### ISSUE TITLE
Training dataset for results mentioned in paper?

### ISSUE THREAD

**Issue by prabhakar267** [mrjleo/boilernet#16]
The details for training dataset for this model are not clearly mentioned in the paper for BoilerNet in the [paper](https://arxiv.org/pdf/2004.14294.pdf). I can find the test dataset results in Table 1 and 2 but not clear on training dataset.

**Comment by mrjleo** [comment]
Hi @prabhakar267,
the train-dev-test splits are included in the dataset zip files found in the README.
In the paper, the splits we used are mentioned in the table captions. For GoogleTrends-2017, this corresponds to `50-30-100-split` and for CleanEval to `ce_split` (in the zip files).

The hyperparameters are here:
https://github.com/mrjleo/boilernet#hyperparameters

**Comment by prabhakar267** [comment]
Thanks for clarification @mrjleo. This was helpful.
