### ISSUE TITLE
Chrome-extension issue

### ISSUE THREAD

**Issue by ttang20913** [mrjleo/boilernet#4]
Hi, why the unpacked chrome-extension crx file is different from the chrome extension folder provided on github?

**Comment by mrjleo** [comment]
Hi, could you elaborate what specifically is different? The .crx contains the built extension and a pre-trained model.

**Comment by ttang20913** [comment]
![image](https://user-images.githubusercontent.com/44049109/98222416-c28f0480-1f8b-11eb-9c67-8522f2f72831.png)
This is the unzipped version of the chrome-extension folder.
The structure is different from the chrome-extension folder on github

**Comment by mrjleo** [comment]
Yeah, this is the built extension (as opposed to the source you see in the repository). You should get the same file structure if you build it yourself.

**Comment by ttang20913** [comment]
OK, thanks for you help.

I have another question.
How can I bypass the chrome extension to get the predictions?
Suppose I have a html file downloaded.
What are the pre-processing steps needed before calling tensorflow's model.predict() function?

**Comment by mrjleo** [comment]
This use case is not implemented, but should be easy enough to do.

You should not use the Chrome extension for this. Instead, load the a pre-trained Keras model and vocabulary and pre-process your html files. You should find the necessary pre-processing functions in net/preprocess.py. Then you can just call the model to get your predictions.

**Comment by ttang20913** [comment]
Thanks for your suggestion. This is how I do the preprocessing.
-------------------------------------
from preprocess import *
import tensorflow as tf

model = tf.keras.models.load_model('model.049.h5')
input = ["test.html"]
doc_representation, tags, words = parse(input)

for doc_feature_list, doc_label_list in get_doc_inputs(doc_representation['test.html'],words,tags):
# not sure how to proceed

------------------------------

In background.js of the chrome extension, function getInputs() will return a tensor.
However, in preprocess.py, function get_doc_inputs(), assuming this is the python version of getInputs(), will return two lists.

So, I am confused on the input format for prediction. 
Can you clarify the input format that is going to parsed to function model.predict(), eg: data type, vector dimensions?
Thanks

**Comment by mrjleo** [comment]
You need to call [get_feature_vector](https://github.com/mrjleo/boilernet/blob/be3a53e59d2449a0220b9f63b204cba4c45da519/net/preprocess.py#L84) for each leaf in the document. Check line 119 in that file. That should give you the correct model inputs.

**Comment by ttang20913** [comment]
I followed you suggestion and now I can get the feature vector. However, the format is still not matching with that of the model.

The error message is 

**ValueError: Error when checking input: expected dense_input to have 3 dimensions, but got array with shape (1052, 1)**

My implementation:

from preprocess import *
import tensorflow as tf

model = tf.keras.models.load_model('net/model.049.h5')
input = ["net/test.html"]



############# get tag and words from training data
filenames = []
filenames.extend(util.get_filenames("datasets/googletrends/prepared_html/"))
data, tags_map, words_map = parse(filenames)

tags_map = get_vocabulary(tags_map, 50)
words_map = get_vocabulary(words_map, 1000)

with open("tags_map.pkl","wb") as f1:
    pickle.dump(tags_map,f1)
with open("words_map.pkl","wb") as f2:
    pickle.dump(words_map,f2)


##############


######## load tag and words

with open("tags_map.pkl","rb") as f1:
       tags_map = pickle.load(f1)
with open("words_map.pkl","rb") as f2:
       words_map = pickle.load(f2)


########


##############  get vector for test.html
result, dummy1, dummy2 = parse(input)


for words_dict, tags_dict, label in result["test.html"]:
        feature_vector = get_feature_vector(words_dict,tags_dict,words_map,tags_map)
        print(feature_vector)
        print("prediction:",model.predict(feature_vector))

**Comment by akhilma-kore** [comment]
@ttang20913 I have a similar requirement is the above issue fixed??

**Comment by akhilma-kore** [comment]
Hi @mrjleo, I am facing the same issue mentioned above by ttang, I copied this piece of code from get_doc_inputs function
`        for words_dict, tags_dict, label in doc:
            feature_vector = get_feature_vector(words_dict, tags_dict, word_map, tag_map)
            doc_features.append(_int64_feature(feature_vector))
            doc_labels.append(_int64_feature([label]))
        doc_feature_list = tf.train.FeatureList(feature=doc_features)
        doc_label_list = tf.train.FeatureList(feature=doc_labels)`
and passing np.array(doc_features_list) to the predict function and I am getting an error like this
**File "/home/akhilmaddala/Documents/kore/Findly-SB/venv-findly/lib/python3.6/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py", line 462, in process_batch_and_step_size
    num_samples = first_x_value.shape[0]
IndexError: tuple index out of range**
can you please guide me on how to fix this issue. Thanks in advance!!!!!

**Comment by mrjleo** [comment]
Hi, please create a new issue for this.
