### ISSUE TITLE
Pre-trained model?

### ISSUE THREAD

**Issue by turian** [mrjleo/boilernet#5]
Is there a way simply to use your pre-trained model? Rather than training again?

**Comment by mrjleo** [comment]
Right now unfortunately the only way is to use the browser extension, but we plan to release an easy to use library in the near future.

**Comment by turian** [comment]
Thank you I will follow this issue.

**Comment by michaelshekasta** [comment]
How do I convert from tf model to tfjs model?

**Comment by mrjleo** [comment]
https://www.tensorflow.org/js/tutorials/conversion/import_keras

**Comment by michaelshekasta** [comment]
Hi, 

Thanks for quick response! I created a model with your code. But, when I tried to install it as a chrome extension, I got errors:
![image](https://user-images.githubusercontent.com/41590425/103628859-3d52ac80-4f48-11eb-9337-3bba23413acf.png)

How do you handle the 3rd party libraries?

**Comment by mrjleo** [comment]
Hi, please make a new issue for this as it has nothing to do with pre-trained models.

**Comment by mrjleo** [comment]
BoilerNet is now available in the SoBigData Method Engine! You can use a pre-trained or your own model to extract text from HTML pages or annotate them directly.

You can find it here: https://sobigdata.d4science.org/group/sobigdatalab/method-engine

**Comment by turian** [comment]
@mrjleo or upload it to zenodo?

**Comment by mrjleo** [comment]
This is strange, I trained the model used by the Chrome extension exactly the same way. Anyway, I uploaded it [here](https://drive.google.com/file/d/198LF14br91YtLpQzwj9I3R3OqG8BMz6X/view?usp=sharing). Hope this helps.

**Comment by mrjleo** [comment]
Hey, I uploaded the model that is used in the SoBigData Service here, which should be the same as the one in the extension I believe.

Unfortunately, I can not check right now. But you can confirm this yourself:

1. [Convert the model to tfjs](https://www.tensorflow.org/js/guide/conversion#convert_your_model)
2. Replace the model in the extension with your converted one
3. Compare the results

I also realized that earlier I forgot to upload the words and tags along with the model. Sorry about that, I updated the link above. Maybe there was a vocabulary mismatch leading to your problem. Please try again with the new files.

**Comment by mrjleo** [comment]
> * Though the dataset and parameters used for training are the same, why do I have different content in the words.json file than the shared one?

If I remember correctly, I trained the model for the extension on both datasets (GT-2017 and CE), leading to a different vocabulary.

> * Can we do incremental training on the model we chose, let's say I have a modern web page with a different template, can I annotate that particular page and use that to train the model?

Yes, certainly. You'd need to load the model before training and make sure your vocabulary matches, though.
