### ISSUE TITLE
Problem with running with class weight

### ISSUE THREAD

**Issue by michaelshekasta** [mrjleo/boilernet#6]
Hi, 

First of all, thanks for sharing your code. There are many packages that you missed like bs4 and downloading staff of NLTK.
When I tried to run the code (training phase), I got an error:
![image](https://user-images.githubusercontent.com/41590425/102889404-441af300-4463-11eb-84c8-fc77fd4353cc.png)

I found that class weight does not represent well (as np array instead of dictionary).
When I change it into the dictionary I got this error:
![image](https://user-images.githubusercontent.com/41590425/102889558-8a705200-4463-11eb-9df1-728ee3f9b8e0.png)

Regards,
Michael

**Comment by mrjleo** [comment]
Hi, could you elaborate? Besides bs4 and NLTK (neither of which are missing from readme or the requirements.txt), what is missing?

Regarding your problem, are you sure you have the correct versions of all packages installed?

**Comment by michaelshekasta** [comment]
1. only bs4 and NLTK (as I remembered)
2. Nope, tensorflow=2.4.0, I also try to run sample_weight but I can't due to using tesorflow files ("Cannot use "sample_weight" in tf.data.Dataset")

**Comment by mrjleo** [comment]
In that case I recommend using Anaconda, I think you should be able to install the correct libraries this way.

**Comment by michaelshekasta** [comment]
which python version? which anaconda version?

**Comment by mrjleo** [comment]
Just check the readme please. It's all there.

**Comment by michaelshekasta** [comment]
Now it's work with that version, but pay attention - when I changed the class weight as a dictionary (as I mentioned before, I got the same error). I am suspect that the class_weight option with np array is a bug.
please take a look at [this thread](https://datascience.stackexchange.com/questions/13490/how-to-set-class-weights-for-imbalanced-classes-in-keras?noredirect=1&lq=1).

**Comment by mrjleo** [comment]
Thanks, it looks like the TF/Keras documentation indeed changed (from array to dict). However I think the way it's done now works properly in TF 2.1. However I did not test it yet. If you find it is indeed a bug, please feel free to open another issue.
